services:
  db:
    image: mongo:8.2.1
    container_name: mymongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_USER_PASSWORD}

volumes:
  mongodb_data:
